{
    "name": "villfa/TryAgain",
    "description": "The TryAgain library permits to call a function again if the result is wrong.",
    "version": "1.0.0",
    "type": "library",
    "keywords": [
        "library",
        "error handling"
    ],
    "homepage": "https://github.com/villfa/TryAgain",
    "license": "MIT",
    "authors": [
        {
            "name": "Fabien Villepinte",
            "email": "fabien.villepinte@gmail.com"
        }
    ],
    "require": {
        "php": "^7.0"
    },
    "require-dev": {
        "mockery/mockery": ">=0.8.0",
        "phpstan/phpstan": "^0.9.2",
        "phpunit/phpunit": "^6.0"
    },
    "autoload": {
        "psr-4": { "TryAgain\\": "src/" }
    },
    "autoload-dev": {
        "psr-4": { "TryAgain\\Tests\\": "tests/" }
    },
    "minimum-stability": "stable"
}
